#I "src/OBO.NET/bin/Debug/netstandard2.0"
#I "src/OBO.NET/bin/Release/netstandard2.0"
#I "src/OBO.NET.CodeGeneration/bin/Debug/netstandard2.0"
#I "src/OBO.NET.CodeGeneration/bin/Release/netstandard2.0"

#r "OBO.NET.dll"
#r "OBO.NET.CodeGeneration.dll"

open OBO.NET
open OBO.NET.DBXref
open OBO.NET.CodeGeneration

#r "nuget: FSharpAux"
#r "nuget: ARCTokenization"

open FSharpAux
open FSharpAux.Regex
open ARCTokenization.Terms

open System

open type System.Environment




type OboOntology =

    {
        Terms                                           : OboTerm list
        TypeDefs                                        : OboTypeDef list
        FormatVersion                                   : string
        DataVersion                                     : string option
        Ontology                                        : string option
        Date                                            : System.DateTime option
        SavedBy                                         : string option
        AutoGeneratedBy                                 : string option
        Subsetdefs                                      : string list
        Imports                                         : string list
        Synonymtypedefs                                 : TermSynonym list           // rethink type, maybe create a mother type (Union?)
        IdSpaces                                        : string list                // rethink as own Record type
        DefaultRelationshipIdPrefix                     : string option
        IdMappings                                      : TermRelation<string> list  // rethink: maybe a new record? or plain string option?
        Remarks                                         : string list
        TreatXrefsAsEquivalents                         : string list
        TreatXrefsAsGenusDifferentias                   : TermRelation<string> list  // rethink: maybe a new record? or plain string option?
        TreatXrefsAsRelationships                       : string list                // maybe better as its own (record/union?) type
        TreatXrefsAsIsAs                                : string list
        RelaxUniqueIdentifierAssumptionForNamespaces    : string list
        RelaxUniqueLabelAssumptionForNamespaces         : string list
    }

    /// Creates an OboOntology based on the given parameters.
    static member create terms typedefs formatVersion dataVersion ontology date savedBy autoGeneratedBy subsetdefs imports synonymtypedefs idSpaces defaultRelationshipIdPrefix idMappings remarks treatXrefsAsEquivalents treatXrefsAsGenusDifferentias treatXrefsAsRelationships treatXrefsAsIsAs relaxUniqueIdentifierAssumptionForNamespaces relaxUniqueLabelAssumptionForNamespaces =
        {
            Terms                                           = terms
            TypeDefs                                        = typedefs
            FormatVersion                                   = formatVersion
            DataVersion                                     = dataVersion
            Ontology                                        = ontology
            Date                                            = date
            SavedBy                                         = savedBy
            AutoGeneratedBy                                 = autoGeneratedBy
            Subsetdefs                                      = subsetdefs
            Imports                                         = imports
            Synonymtypedefs                                 = synonymtypedefs
            IdSpaces                                        = idSpaces
            DefaultRelationshipIdPrefix                     = defaultRelationshipIdPrefix
            IdMappings                                      = idMappings
            Remarks                                         = remarks
            TreatXrefsAsEquivalents                         = treatXrefsAsEquivalents
            TreatXrefsAsGenusDifferentias                   = treatXrefsAsGenusDifferentias
            TreatXrefsAsRelationships                       = treatXrefsAsRelationships
            TreatXrefsAsIsAs                                = treatXrefsAsIsAs
            RelaxUniqueIdentifierAssumptionForNamespaces    = relaxUniqueIdentifierAssumptionForNamespaces
            RelaxUniqueLabelAssumptionForNamespaces         = relaxUniqueLabelAssumptionForNamespaces
        }

    /// Creates an OboOntology based on the given arguments.
    static member Create(terms, typedefs, formatVersion, ?DataVersion, ?Ontology, ?Date, ?SavedBy, ?AutoGeneratedBy, ?Subsetdefs, ?Imports, ?Synonymtypedefs, ?IdSpaces, ?DefaultRelationshipIdPrefix, ?IdMappings, ?Remarks, ?TreatXrefsAsEquivalents, ?TreatXrefsAsGenusDifferentias, ?TreatXrefsAsRelationships, ?TreatXrefsAsIsAs, ?RelaxUniqueIdentifierAssumptionForNamespaces, ?RelaxUniqueLabelAssumptionForNamespaces) = {
        Terms                                           = terms
        TypeDefs                                        = typedefs
        FormatVersion                                   = formatVersion
        DataVersion                                     = DataVersion
        Ontology                                        = Ontology
        Date                                            = Date
        SavedBy                                         = SavedBy
        AutoGeneratedBy                                 = AutoGeneratedBy
        Subsetdefs                                      = defaultArg Subsetdefs []
        Imports                                         = defaultArg Imports []
        Synonymtypedefs                                 = defaultArg Synonymtypedefs []
        IdSpaces                                        = defaultArg IdSpaces []
        DefaultRelationshipIdPrefix                     = DefaultRelationshipIdPrefix
        IdMappings                                      = defaultArg IdMappings []
        Remarks                                         = defaultArg Remarks []
        TreatXrefsAsEquivalents                         = defaultArg TreatXrefsAsEquivalents []
        TreatXrefsAsGenusDifferentias                   = defaultArg TreatXrefsAsGenusDifferentias []
        TreatXrefsAsRelationships                       = defaultArg TreatXrefsAsRelationships []
        TreatXrefsAsIsAs                                = defaultArg TreatXrefsAsIsAs []
        RelaxUniqueIdentifierAssumptionForNamespaces    = defaultArg RelaxUniqueIdentifierAssumptionForNamespaces []
        RelaxUniqueLabelAssumptionForNamespaces         = defaultArg RelaxUniqueLabelAssumptionForNamespaces []
    }

//let res = (createRegex RegexOptions.None """format-version\s:\s*(?<formatVersion>.+)""").Match "format-version : 17.5.1"
//let res = (createRegex RegexOptions.None """format-version\s:\s*(?<formatVersion>.+)""").Match "format-verson: 17.5.1"
//res.Groups["formatVersion"].Value
//DateTime.ParseExact("31:12:2000 23:59", "dd:MM:yyyy HH:mm", Globalization.CultureInfo.InvariantCulture)

    /// Reads an OBO Ontology containing term and type def stanzas from lines.
    static member fromLines verbose (input : seq<string>) =

        let rxFormatVersion     = createRegex RegexOptions.None @"format-version\s*:\s*(?<formatVersion>.+)"
        let rxDataVersion       = createRegex RegexOptions.None @"(?:data-version|version)\s*:\s*(?<dataVersion>.+)"
        let rxOntology          = createRegex RegexOptions.None @"ontology\s*:\s*(?<ontology>.+)"
        let rxDate              = createRegex RegexOptions.None @"date\s*:\s*(?<date>\d{2}:\d{2}:\d{4} \d{2}:\d{2})"
        let rxSavedBy           = createRegex RegexOptions.None @"saved-by\s*:\s*(?<savedBy>.+)"
        let rxAutoGeneratedBy   = createRegex RegexOptions.None @"auto-generated-by\s*:\s*(?<autoGeneratedBy>.+)"

        let en = input.GetEnumerator()

        let rec loop (en : System.Collections.Generic.IEnumerator<string>) terms typedefs formatVersion (dataVersion : string option) ontology date savedBy autoGeneratedBy subsetdefs imports synonymtypedefs idSpaces defaultRelationshipIdPrefix idMappings remarks treatXrefsAsEquivalents treatXrefsAsIsAs relaxUniqueIdentifierAssumptionForNamespaces relaxUniqueLabelAssumptionForNamespaces lineNumber =

            match en.MoveNext() with
            | true ->             
                match trimComment en.Current with
                | "[Term]"    -> 
                    let lineNumber,parsedTerm = OboTerm.fromLines verbose en lineNumber "" "" false [] "" "" [] [] [] [] [] [] [] [] false [] [] [] false "" ""
                    loop en (parsedTerm :: terms) typedefs formatVersion dataVersion ontology date savedBy autoGeneratedBy subsetdefs imports synonymtypedefs idSpaces defaultRelationshipIdPrefix idMappings remarks treatXrefsAsEquivalents treatXrefsAsIsAs relaxUniqueIdentifierAssumptionForNamespaces relaxUniqueLabelAssumptionForNamespaces lineNumber
                | "[Typedef]" -> 
                    let lineNumber,parsedTypeDef = OboTypeDef.fromLines verbose en lineNumber "" "" "" "" [] [] false false false false false false false
                    loop en terms (parsedTypeDef :: typedefs) formatVersion dataVersion ontology date savedBy autoGeneratedBy subsetdefs imports synonymtypedefs idSpaces defaultRelationshipIdPrefix idMappings remarks treatXrefsAsEquivalents treatXrefsAsIsAs relaxUniqueIdentifierAssumptionForNamespaces relaxUniqueLabelAssumptionForNamespaces lineNumber
                | x when (rxFormatVersion.Match x).Success -> 
                    if formatVersion <> "" then printfn "WARN: Duplicate format-version!"
                    loop en terms typedefs (rxFormatVersion.Match x).Groups["formatVersion"].Value dataVersion ontology date savedBy autoGeneratedBy subsetdefs imports synonymtypedefs idSpaces defaultRelationshipIdPrefix idMappings remarks treatXrefsAsEquivalents treatXrefsAsIsAs relaxUniqueIdentifierAssumptionForNamespaces relaxUniqueLabelAssumptionForNamespaces (lineNumber + 1)
                | x when (rxDataVersion.Match x).Success ->
                    if dataVersion.IsSome then printfn "WARN: Duplicate data-version!"
                    loop en terms typedefs formatVersion (Some (rxDataVersion.Match x).Groups["dataVersion"].Value) ontology date savedBy autoGeneratedBy subsetdefs imports synonymtypedefs idSpaces defaultRelationshipIdPrefix idMappings remarks treatXrefsAsEquivalents treatXrefsAsIsAs relaxUniqueIdentifierAssumptionForNamespaces relaxUniqueLabelAssumptionForNamespaces (lineNumber + 1)
                | x when (rxOntology.Match x).Success ->
                    loop en terms typedefs formatVersion dataVersion (rxOntology.Match x).Groups["ontology"] date savedBy autoGeneratedBy subsetdefs imports synonymtypedefs idSpaces defaultRelationshipIdPrefix idMappings remarks treatXrefsAsEquivalents treatXrefsAsIsAs relaxUniqueIdentifierAssumptionForNamespaces relaxUniqueLabelAssumptionForNamespaces (lineNumber + 1)
                | x when (rxDate.Match x).Success -> 
                    let parsedDate = 
                        try DateTime.ParseExact((rxDate.Match x).Groups["date"].Value, "dd:MM:yyyy HH:mm", Globalization.CultureInfo.InvariantCulture) |> Some with
                            _ -> 
                                printfn "ERROR: Inproper date given!"
                                None
                    loop en terms typedefs formatVersion dataVersion ontology parsedDate savedBy autoGeneratedBy subsetdefs imports synonymtypedefs idSpaces defaultRelationshipIdPrefix idMappings remarks treatXrefsAsEquivalents treatXrefsAsIsAs relaxUniqueIdentifierAssumptionForNamespaces relaxUniqueLabelAssumptionForNamespaces (lineNumber + 1)
                | x when String.startsWith "saved-by" x -> 
                    loop en terms typedefs formatVersion dataVersion ontology date (skipColonSpace enTrimmed |> Some) autoGeneratedBy subsetdefs imports synonymtypedefs idSpaces defaultRelationshipIdPrefix idMappings remarks treatXrefsAsEquivalents treatXrefsAsIsAs relaxUniqueIdentifierAssumptionForNamespaces relaxUniqueLabelAssumptionForNamespaces (lineNumber + 1)
                | x when String.startsWith "auto-generated-by" x -> 
                    loop en terms typedefs formatVersion dataVersion ontology date savedBy (skipColonSpace enTrimmed |> Some) subsetdefs imports synonymtypedefs idSpaces defaultRelationshipIdPrefix idMappings remarks treatXrefsAsEquivalents treatXrefsAsIsAs relaxUniqueIdentifierAssumptionForNamespaces relaxUniqueLabelAssumptionForNamespaces (lineNumber + 1)
                | x when String.startsWith "subsetdef" x -> 
                    loop en terms typedefs formatVersion dataVersion ontology date savedBy autoGeneratedBy (skipColonSpace enTrimmed :: subsetdefs) imports synonymtypedefs idSpaces defaultRelationshipIdPrefix idMappings remarks treatXrefsAsEquivalents treatXrefsAsIsAs relaxUniqueIdentifierAssumptionForNamespaces relaxUniqueLabelAssumptionForNamespaces (lineNumber + 1)
                | x when String.startsWith "import" x -> 
                    loop en terms typedefs formatVersion dataVersion ontology date savedBy autoGeneratedBy subsetdefs (enTrimmed :: imports) synonymtypedefs idSpaces defaultRelationshipIdPrefix idMappings remarks treatXrefsAsEquivalents treatXrefsAsIsAs relaxUniqueIdentifierAssumptionForNamespaces relaxUniqueLabelAssumptionForNamespaces (lineNumber + 1)
                | x when String.startsWith "synonymtypedef" x -> 
                    loop en terms typedefs formatVersion dataVersion ontology date savedBy autoGeneratedBy subsetdefs imports synonymtypedefs idSpaces defaultRelationshipIdPrefix idMappings remarks treatXrefsAsEquivalents treatXrefsAsIsAs relaxUniqueIdentifierAssumptionForNamespaces relaxUniqueLabelAssumptionForNamespaces (lineNumber + 1)
                | _ -> 
                    loop en terms typedefs formatVersion dataVersion ontology date savedBy autoGeneratedBy subsetdefs imports synonymtypedefs idSpaces defaultRelationshipIdPrefix idMappings remarks treatXrefsAsEquivalents treatXrefsAsIsAs relaxUniqueIdentifierAssumptionForNamespaces relaxUniqueLabelAssumptionForNamespaces (lineNumber + 1)
                | _ -> 
                    loop en terms typedefs formatVersion dataVersion ontology date savedBy autoGeneratedBy subsetdefs imports synonymtypedefs idSpaces defaultRelationshipIdPrefix idMappings remarks treatXrefsAsEquivalents treatXrefsAsIsAs relaxUniqueIdentifierAssumptionForNamespaces relaxUniqueLabelAssumptionForNamespaces (lineNumber + 1)
                | _ -> 
                    loop en terms typedefs formatVersion dataVersion ontology date savedBy autoGeneratedBy subsetdefs imports synonymtypedefs idSpaces defaultRelationshipIdPrefix idMappings remarks treatXrefsAsEquivalents treatXrefsAsIsAs relaxUniqueIdentifierAssumptionForNamespaces relaxUniqueLabelAssumptionForNamespaces (lineNumber + 1)
                | _ -> 
                    loop en terms typedefs formatVersion dataVersion ontology date savedBy autoGeneratedBy subsetdefs imports synonymtypedefs idSpaces defaultRelationshipIdPrefix idMappings remarks treatXrefsAsEquivalents treatXrefsAsIsAs relaxUniqueIdentifierAssumptionForNamespaces relaxUniqueLabelAssumptionForNamespaces (lineNumber + 1)
                | _ -> 
                    loop en terms typedefs formatVersion dataVersion ontology date savedBy autoGeneratedBy subsetdefs imports synonymtypedefs idSpaces defaultRelationshipIdPrefix idMappings remarks treatXrefsAsEquivalents treatXrefsAsIsAs relaxUniqueIdentifierAssumptionForNamespaces relaxUniqueLabelAssumptionForNamespaces (lineNumber + 1)
                | _ -> 
                    loop en terms typedefs formatVersion dataVersion ontology date savedBy autoGeneratedBy subsetdefs imports synonymtypedefs idSpaces defaultRelationshipIdPrefix idMappings remarks treatXrefsAsEquivalents treatXrefsAsIsAs relaxUniqueIdentifierAssumptionForNamespaces relaxUniqueLabelAssumptionForNamespaces (lineNumber + 1)
                | _ -> 
                    loop en terms typedefs formatVersion dataVersion ontology date savedBy autoGeneratedBy subsetdefs imports synonymtypedefs idSpaces defaultRelationshipIdPrefix idMappings remarks treatXrefsAsEquivalents treatXrefsAsIsAs relaxUniqueIdentifierAssumptionForNamespaces relaxUniqueLabelAssumptionForNamespaces (lineNumber + 1)
                | _ -> 
                    loop en terms typedefs formatVersion dataVersion ontology date savedBy autoGeneratedBy subsetdefs imports synonymtypedefs idSpaces defaultRelationshipIdPrefix idMappings remarks treatXrefsAsEquivalents treatXrefsAsIsAs relaxUniqueIdentifierAssumptionForNamespaces relaxUniqueLabelAssumptionForNamespaces (lineNumber + 1)
            | false -> 
                OboOntology.create (List.rev terms) (List.rev typedefs) formatVersion dataVersion ontology date savedBy autoGeneratedBy (List.rev subsetdefs) (List.rev imports) (List.rev synonymtypedefs) (List.rev idSpaces) defaultRelationshipIdPrefix idMappings remarks treatXrefsAsEquivalents treatXrefsAsIsAs relaxUniqueIdentifierAssumptionForNamespaces relaxUniqueLabelAssumptionForNamespaces

        loop en [] [] String.Empty None None None None None [] [] [] [] None [] [] [] [] [] [] 0    // was 1 before

DateTime.parse "24:04:2024 08:01"
System.DateTime.ParseExact("24:04:2024 08:01", "dd:MM:yyyy HH:mm", System.Globalization.CultureInfo.InvariantCulture)




let expected = 
    $"namespace ARCTokenization.StructuralOntology{NewLine}{NewLine}    open ControlledVocabulary{NewLine}{NewLine}    module Investigation ={NewLine}{NewLine}        let Investigation_Metadata = CvTerm.create(\"INVMSO:00000001\", \"Investigation Metadata\", \"INVMSO\"){NewLine}{NewLine}        let ONTOLOGY_SOURCE_REFERENCE = CvTerm.create(\"INVMSO:00000002\", \"ONTOLOGY SOURCE REFERENCE\", \"INVMSO\"){NewLine}{NewLine}        let Term_Source_Name = CvTerm.create(\"INVMSO:00000003\", \"Term Source Name\", \"INVMSO\")"
    |> String.replace "\r" ""
let actual = 
    CodeGeneration.toSourceCode "Investigation" InvestigationMetadata.ontology 
    |> String.splitS NewLine 
    |> Array.take 11 
    |> String.concat "\n"
    |> String.replace "\r" ""

OBO.NET.OboOntology.toFile @"C:\Repos\CSBiology\OBO.NET\tests\OBO.NET.CodeGeneration.Tests\References\ReferenceOboFile.obo" InvestigationMetadata.ontology


// DEPRECATED


#I "src/FsOboParser/bin/Debug/netstandard2.0"
#I "src/FsOboParser/bin/Release/netstandard2.0"
#r "FsOboParser.dll"

#r "nuget: IsaDotNet"
//#r "nuget: FsOboParser"
#r "nuget: FSharpAux"


open FsOboParser

open FSharpAux

open System.IO


//let testPath = Path.Combine(__SOURCE_DIRECTORY__,  "./../../nfdi4plants/arc-validate/ErrorClassOntology.obo")

//OboEntries.fromFile true testPath
//let testOntology = OboOntology.fromFile true testPath

let testTerms = [
    OboTerm.Create("test:000", Name = "test0")
    OboTerm.Create("test:001", Name = "test1a", IsA = ["test:000"])
    OboTerm.Create("test:002", Name = "test2", IsA = ["test:001"; "test:000"])
    OboTerm.Create("test:003", Name = "test1b", IsA = ["test:000"])
    OboTerm.Create("test:004", Name = "test1aSyn", Synonyms = [TermSynonym.parseSynonym None 1 "\"test1a\" EXACT []"])
    //OboTerm.Create("test:004", Name = "test1aSyn", Synonyms = [TermSynonym.parseSynonym None 1 "test1a EXACT []"])
]

let testOntology = OboOntology.create testTerms []



//let termOfInterest = testOntology.Terms[5]
//let targetOfInterest = testOntology.Terms[7]

//let emptyTermRelation = Empty termOfInterest
//let targetMissingTermRelation = TargetMissing ("unconnected_to", termOfInterest)
//let targetTermRelation = Target ("connected_to", termOfInterest, targetOfInterest)

//// exemplary
//type MyRelation =
//    | IsA
//    | HasA
//    | PartOf
//    | ConnectedTo
//    | Unknown of string

//let targetTermRelation' = Target (ConnectedTo, termOfInterest, targetOfInterest)



///// Takes a given OboTerm and returns a sequence of scope * OboTerm if the synonym exists in the given OboOntology or scope * None if it does not.
//let tryGetSynonymTerms (term : OboTerm) (onto : OboOntology) =
//    term.Synonyms
//    |> Seq.map (
//        fun s -> 
//            s.Scope,
//            onto.Terms 
//            |> Seq.tryFind (
//                fun t -> 
//                    t.Name = String.replace "\"" "" s.Text
//            )
//    )

///// Takes a given OboTerm and returns a sequence of scope * OboTerm if the synonym exists in the given OboOntology.
//let getSynonymTerms (term : OboTerm) (onto : OboOntology) =
//    term.Synonyms
//    |> Seq.choose (
//        fun s -> 
//            let sto =
//                onto.Terms 
//                |> Seq.tryFind (
//                    fun t -> 
//                        t.Name = String.replace "\"" "" s.Text
//                )
//            match sto with
//            | Some st -> Some (s.Scope, st)
//            | None -> None
//    )

//String.replace "\"" "" (TermSynonym.parseSynonym None 1 "test1a EXACT []").Text

//tryGetSynonymTerms testTerms[4] testOntology
//getSynonymTerms testTerms[4] testOntology


//OboOntology.getRelations testOntology


//testOntology.GetChildOntologyAnnotations(testTerms.Head.Id)
//testOntology.GetChildOntologyAnnotations(testTerms.Head.Id, Depth = 1)
//testOntology.GetChildOntologyAnnotations(testTerms.Head.Id, Depth = 2)



//let performanceTerms = List.init 7000000 (fun i -> OboTerm.Create($"lol:{i}"))
//let performanceOboOntology = OboOntology.create performanceTerms []
//OboOntology.toFile @"C:\Repos\CSBiology\FsOboParser\performanceOntology.obo" performanceOboOntology

//let x = OboOntology.fromFile false @"C:\Repos\CSBiology\FsOboParser\performanceOntology.obo"


//let fileLines = File.ReadAllLines testPath

//OboTerm.fromLines true ((fileLines |> Seq.ofArray).GetEnumerator()) 0

//OboOntology.toFile "myOboOntology.obo" testOboOntology

//Path.Combine("myOboOntology.obo") |> FileInfo

//let myOboTerm = OboTerm.Create("TO:00000000", Name = "testTerm", CreatedBy = "myself")

//let myOboTerm = 
//    OboTerm.create 
//        "TO:00000000" 
//        (Some "testTerm") 
//        None 
//        None 
//        None 
//        None 
//        None 
//        None 
//        None 
//        None 
//        None 
//        None 
//        None 
//        None 
//        None 
//        None 
//        None 
//        None 
//        None 
//        (Some "myself") 
//        None

//OboTypeDef.Create

//let myOntology = OboOntology.create [myOboTerm] []

//OboOntology.toFile "myOboOntology.obo" myOntology

//let termOfInterest = testOntology.Terms[5]

//let isAs = testOntology.GetParentOntologyAnnotations(termOfInterest.Id)
// output is an ISADotNet.OntologyAnnotation list

//let isAsTerms = isAs |> List.map (fun oa -> testOntology.GetTerm(oa.TermAccessionString.ToString()))
// output is an OboTerm list